//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMetodosVarios
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMetodosVarios.IMetodosVariados")]
    public interface IMetodosVariados
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodosVariados/GetTablaMultiplicar", ReplyAction="http://tempuri.org/IMetodosVariados/GetTablaMultiplicarResponse")]
        System.Threading.Tasks.Task<int[]> GetTablaMultiplicarAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodosVariados/GetSaludo", ReplyAction="http://tempuri.org/IMetodosVariados/GetSaludoResponse")]
        System.Threading.Tasks.Task<string> GetSaludoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodosVariados/GetNumeroDoble", ReplyAction="http://tempuri.org/IMetodosVariados/GetNumeroDobleResponse")]
        System.Threading.Tasks.Task<int> GetNumeroDobleAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMetodosVariadosChannel : ServiceMetodosVarios.IMetodosVariados, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MetodosVariadosClient : System.ServiceModel.ClientBase<ServiceMetodosVarios.IMetodosVariados>, ServiceMetodosVarios.IMetodosVariados
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MetodosVariadosClient() : 
                base(MetodosVariadosClient.GetDefaultBinding(), MetodosVariadosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMetodosVariados.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetodosVariadosClient(EndpointConfiguration endpointConfiguration) : 
                base(MetodosVariadosClient.GetBindingForEndpoint(endpointConfiguration), MetodosVariadosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetodosVariadosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MetodosVariadosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetodosVariadosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MetodosVariadosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetodosVariadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int[]> GetTablaMultiplicarAsync(int numero)
        {
            return base.Channel.GetTablaMultiplicarAsync(numero);
        }
        
        public System.Threading.Tasks.Task<string> GetSaludoAsync(string nombre)
        {
            return base.Channel.GetSaludoAsync(nombre);
        }
        
        public System.Threading.Tasks.Task<int> GetNumeroDobleAsync(int numero)
        {
            return base.Channel.GetNumeroDobleAsync(numero);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMetodosVariados))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMetodosVariados))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:58347/ServiceMetodosVarios.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MetodosVariadosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMetodosVariados);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MetodosVariadosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMetodosVariados);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMetodosVariados,
        }
    }
}
